# App Info
ios_app_id                                : 1455793030                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Write a short tagline for your app.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Gonzo Fialho (gonzula)
your_link                                 : https://github.com/gonzula
your_city                                 : SÃ£o Carlos
email_address                             : carlos@ceafdc.com
facebook_username                         :
instagram_username                        :
twitter_username                          : gonzula_f
github_username                           : gonzula
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Real Programming Language
    description                           : Splash is a programming language that compiles to a fully working, native Siri Shortcut.
    fontawesome_icon_name                 : stream

  - title                                 : iOS App
    description                           : With a native iOS app, that contains a text editor and the Splash compiler, you can write your scripts and run them without leaving your phone.
    fontawesome_icon_name                 : mobile

  - title                                 : Desktop Compiler
    description                           : If you prefer to write your code on the computer, you can totally do so with the splash compiler for desktop. It runs on any OS.
    fontawesome_icon_name                 : desktop

  - title                                 : Sync
    description                           : The iOS app comes with a file browser that syncs your scripts with all major cloud services.
    fontawesome_icon_name                 : sync

  - title                                 : Light/Dark mode
    description                           : The app has two (at the moment) different themes. More to come!
    fontawesome_icon_name                 : adjust

  - title                                 : Free Software/Open Source
    description                           : The app, the compiler and the language as a whole. Everything is free software under GPL3.
    fontawesome_icon_name                 : osi

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
